// ----------------------------------------------------------------------------
// <auto-generated>
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
// </auto-generated>
// ----------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Security;
using __CallingConvention = global::System.Runtime.InteropServices.CallingConvention;
using __IntPtr = global::System.IntPtr;

#pragma warning disable CS0109 // Member does not hide an inherited member; new keyword is not required

namespace AssimpNet.Unmanaged
{
    /// <summary>
    /// <para>Enumerates components of the aiScene and aiMesh data structures</para>
    /// <para>that can be excluded from the import using the #aiProcess_RemoveComponent step.</para>
    /// </summary>
    /// <remarks>See the documentation to #aiProcess_RemoveComponent for more details.</remarks>
    public enum Component
    {
        ComponentNORMALS = 2,
        ComponentTANGENTS_AND_BITANGENTS = 4,
        /// <summary>
        /// <para>ALL color sets</para>
        /// <para>Use aiComponent_COLORn(N) to specify the N'th set</para>
        /// </summary>
        ComponentCOLORS = 8,
        /// <summary>
        /// <para>ALL texture UV sets</para>
        /// <para>aiComponent_TEXCOORDn(N) to specify the N'th set</para>
        /// </summary>
        ComponentTEXCOORDS = 16,
        /// <summary>
        /// <para>Removes all bone weights from all meshes.</para>
        /// <para>The scenegraph nodes corresponding to the bones are NOT removed.</para>
        /// <para>use the #aiProcess_OptimizeGraph step to do this</para>
        /// </summary>
        ComponentBONEWEIGHTS = 32,
        /// <summary>
        /// <para>Removes all node animations (aiScene::mAnimations).</para>
        /// <para>The corresponding scenegraph nodes are NOT removed.</para>
        /// <para>use the #aiProcess_OptimizeGraph step to do this</para>
        /// </summary>
        ComponentANIMATIONS = 64,
        /// <summary>Removes all embedded textures (aiScene::mTextures)</summary>
        ComponentTEXTURES = 128,
        /// <summary>
        /// <para>Removes all light sources (aiScene::mLights).</para>
        /// <para>The corresponding scenegraph nodes are NOT removed.</para>
        /// <para>use the #aiProcess_OptimizeGraph step to do this</para>
        /// </summary>
        ComponentLIGHTS = 256,
        /// <summary>
        /// <para>Removes all cameras (aiScene::mCameras).</para>
        /// <para>The corresponding scenegraph nodes are NOT removed.</para>
        /// <para>use the #aiProcess_OptimizeGraph step to do this</para>
        /// </summary>
        ComponentCAMERAS = 512,
        /// <summary>Removes all meshes (aiScene::mMeshes).</summary>
        ComponentMESHES = 1024,
        /// <summary>
        /// <para>Removes all materials. One default material will</para>
        /// <para>be generated, so aiScene::mNumMaterials will be 1.</para>
        /// </summary>
        ComponentMATERIALS = 2048,
        AiComponentForce32Bit = -1610612737
    }
}
